# Remplace par ton vrai projectKey et organization (sonarcloud.io)
sonar.projectKey=Milhane41_Projet_Final
sonar.organization=milhane41
sonar.projectName=Projet_Final

sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
