sonar.projectKey=ousmane-fall_Projet-usine-logicielle
sonar.organization=ousmane-fall
sonar.projectName=Projet-usine-logicielle

sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
