# Inventory généré automatiquement par le workflow CD
# Pour usage local : remplace l'IP par celle de ta VM Azure
# (récupérable avec : terraform output vm_public_ip)
[servers]
taskflow-vm ansible_host=AZURE_VM_IP ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa

[servers:vars]
ansible_python_interpreter=/usr/bin/python3
